# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Ramkrishna Medical Complex
email: ramkrishnamedicalcomplex@gmail.com
tagline: Multispeciality Nursing Home and Doctor Outdoor Unit 
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://ramkrishnamedicalcomplex.com" # the base hostname & protocol for your site
phone: 7059702169
google_maps: https://goo.gl/maps/Ps1HcxnjR9L2
address: 132/2/12, Maulana Abul Kalam Azad Sarani Near Sri Gurudas Banerjee Halt, Phool Bagan, Kankurgachi, Kolkata, West Bengal 700054

services:
  - Medicine
  - Chest and Respitory
  - Diabetic and Endocrinology
  - Cardialogy
  - Paediactric 
  - Oncology
  - Surgery
  - Orthopedic
  - Gyne
  - Dental Surgery
  - Modern Operation Theatre
  - HDU / ICCU
  - General Ward
  - AC/Non AC Cabin
  - Pathology 
  - Ambulance 

collections: 
  - doctors


# Build settings
markdown: kramdown
sass:
    sass_dir: ./css
